
import React from 'react';

export const COLORS = {
  dark: {
    mainBg: '#0a0a0f',
    sidebarBg: '#111827',
    bubbleSelf: '#1e3a8a',
    bubbleOther: '#1f2937',
    accent: '#0611ff',
    accentHover: '#3b3bff',
    secondaryText: '#94a3b8',
    mainText: '#f1f5f9',
    border: '#1e293b',
    online: '#22c55e',
    error: '#E44444',
  },
  light: {
    mainBg: '#f8fafc',
    sidebarBg: '#ffffff',
    bubbleSelf: '#dbeafe',
    bubbleOther: '#ffffff',
    accent: '#0611ff',
    accentHover: '#3b3bff',
    secondaryText: '#64748b',
    mainText: '#0f172a',
    border: '#e2e8f0',
    online: '#16a34a',
    error: '#DC2626',
  }
};

export const AVATAR_GRADIENTS = [
  'from-blue-500 to-indigo-600',
  'from-slate-500 to-slate-700',
  'from-gray-600 to-gray-800',
  'from-blue-700 to-blue-900',
];

export const TRANSLATIONS = {
  en: {
    search: 'Search',
    newGroup: 'New Group',
    contacts: 'Contacts',
    calls: 'Calls',
    savedMessages: 'Saved Messages',
    settings: 'Settings',
    nightMode: 'Night Mode',
    online: 'online',
    offline: 'offline',
    typing: 'typing...',
    send: 'Send',
    reply: 'Reply',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    deleteChat: 'Delete Chat',
    clearHistory: 'Clear History',
    mute: 'Mute Notifications',
    sharedMedia: 'Shared Media',
    noChatSelected: 'Select a chat to start messaging',
    editProfile: 'Edit Profile',
    addContact: 'Add Contact',
    enterId: 'Enter Unique ID',
    myId: 'My ID',
    copied: 'Copied!',
    language: 'Language',
    placeholderGroupName: 'Group Name',
    noCalls: 'No recent calls',
    calling: 'Calling...',
    endCall: 'End Call',
    userNotFound: 'User ID not found in database',
    searchMessages: 'Search messages...',
    create: 'Create',
  },
  ru: {
    search: 'Поиск',
    newGroup: 'Новая группа',
    contacts: 'Контакты',
    calls: 'Звонки',
    savedMessages: 'Избранное',
    settings: 'Настройки',
    nightMode: 'Ночной режим',
    online: 'в сети',
    offline: 'не в сети',
    typing: 'печатает...',
    send: 'Отправить',
    reply: 'Ответить',
    edit: 'Изм.',
    save: 'Сохранить',
    cancel: 'Отмена',
    deleteChat: 'Удалить чат',
    clearHistory: 'Очистить историю',
    mute: 'Уведомления',
    sharedMedia: 'Общие медиа',
    noChatSelected: 'Выберите чат для общения',
    editProfile: 'Изм. профиль',
    addContact: 'Добавить контакт',
    enterId: 'Введите уникальный ID',
    myId: 'Мой ID',
    copied: 'Скопировано!',
    language: 'Язык',
    placeholderGroupName: 'Название группы',
    noCalls: 'Нет недавних звонков',
    calling: 'Звонок...',
    endCall: 'Завершить',
    userNotFound: 'ID пользователя не найден',
    searchMessages: 'Поиск по сообщениям...',
    create: 'Создать',
  }
};

export const GEMINI_USER = {
  id: 'gemini-ai-bot',
  name: 'Gemini AI',
  status: 'online' as const,
  bio: 'Professional Virtual Assistant.',
};
